[test]
# always enable coverage
coverage = true
# to require 90% line-level and function-level coverage
coverageThreshold = 0.9

[install]
registry = "https://registry.npmmirror.com"
# Keep pnpm-like node_modules layout for Bun
linker = "isolated"
